In [4]:
from ipycanvas import Canvas, hold_canvas,RoughCanvas
import numpy
shape = [500,500]
canvas = Canvas(width=shape[0], height=shape[1])
canvas

Canvas(width=500)

In [38]:
canvas.clear()
with hold_canvas(canvas):
    points = [
        [
            [0,0], [0,100],[100,100]
        ],
        [
            [200,0], [200,100],[300,100],[200,0]
        ],
        [
            [200,200],[200,410],[410,410],[200,200]
        ]
    ]
    n_poly = len(points)
    colors = numpy.random.randint(low=0, high=255, size=(n_poly,3), dtype='uint8')
    alpha = numpy.random.rand(n_poly)
    canvas.batch_fill_polygons(points,colors, alpha)
    canvas.line_width = 10
    colors = numpy.random.randint(low=0, high=255, size=(n_poly,3), dtype='uint8')
    canvas.batch_stroke_line_segments(points,colors, alpha)

[[ 35 224 216]
 [113  24  15]
 [ 46 214 143]]
[0.3184802  0.34435892 0.99006774]
[  0   0   0 100 100 100 200   0 200 100 300 100 200   0 200 200 200 410
 410 410 200 200]
[  0   0   0 100 100 100 200   0 200 100 300 100 200   0 200 200 200 410
 410 410 200 200]


In [10]:
n = 1000
with hold_canvas(canvas):
    x = numpy.random.rand(n)* shape[0]
    y = numpy.random.rand(n)* shape[0]
    r = numpy.random.rand(n)* 10.0
    colors = numpy.random.randint(low=0, high=255, size=(n,3), dtype='uint8')
    alpha = numpy.random.rand(n)
    canvas.batch_fill_circles(x,y,r,colors.ravel(), alpha)
    # canvas.fill_rect(10,20, 10,20)
